var someHumanData = {
  // trade
  TransportCapacity: {
    eng: `Cargo Bay Extension`,
  },
  ShipmentComputer: { eng: `Shipment Computer` },
  Trader: { eng: `Trade Boost` },
  Rush: { eng: `Rush` },
  TradeBurst: { eng: `Trade Burst` },
  ShipmentDrone: { eng: `Shipment Drone` },
  Offload: { eng: `Offload` },
  ShipmentBeam: { eng: `Shipment Beam` },
  Entrust: { eng: `Entrust` },
  Dispatch: { eng: `Dispatch` },
  Recall: { eng: `Recall` },

  // mining
  MiningBoost: { eng: `Mining Boost` },
  MineralStorageCapacity: {
    eng: `Hydrogen Bay Extension`,
  },
  Enrich: { eng: `Enrich` },
  MassMining: { eng: `Remote Mining` },
  HydrogenUpload: { eng: `Hydrogen Upload` },
  MiningUnity: { eng: `Mining Unity` },
  Crunch: { eng: `Crunch` },
  Genesis: { eng: `Genesis` },
  MiningDrone: { eng: `Mining Drone` },
  HydroRocket: { eng: `Hydro Rocket` },

  //  weapon
  WeakBattery: { eng: `Weak Battery` },
  Battery: { eng: `Battery` },
  Laser: { eng: `Laser` },
  MassBattery: { eng: `Mass Battery` },
  DualLaser: { eng: `Dual Laser` },
  Barrage: { eng: `Barrage` },
  DartLauncher: { eng: `Dart Launcher` },

  //  shield
  WeakShield: { eng: `Alpha Shield` },
  StandardShield: { eng: `Delta Shield` },
  PassiveShield: { eng: `Passive Shield` },
  StrongShield: { eng: `Omega Shield` },
  MirrorShield: { eng: `Mirror Shield` },
  BlastShield: { eng: `Blast Shield` },
  AreaShield: { eng: `Area Shield` },

  // support
  EMP: { eng: `EMP` },
  Teleport: { eng: `Teleport` },
  RedStarExtender: {
    eng: `Red Star Life Extender`,
  },
  Repair: { eng: `Remote Repair` },
  TimeWarp: { eng: `Time Warp` },
  Unity: { eng: `Unity` },
  Sanctuary: { eng: `Sanctuary` },
  Stealth: { eng: `Stealth` },
  Fortify: { eng: `Fortify` },
  Impulse: { eng: `Impulse` },
  AlphaRocket: { eng: `AlphaRocket` },
  Salvage: { eng: `Salvage` },
  Supress: { eng: `Suppress` },
  Destiny: { eng: `Destiny` },
  Barrier: { eng: `Barrier` },
  Vengeance: { eng: `Vengeance` },
  DeltaRocket: { eng: `Delta Rocket` },
  Leap: { eng: `Leap` },
  Bond: { eng: `Bond` },
  AlphaDrone: { eng: `Alpha Drone` },
  OmegaRocket: { eng: `Omega Rocket` },
};

var modulesByTypes = {
  trade: [
    'TransportCapacity',
    'ShipmentComputer',
    'Trader',
    'Rush',
    'TradeBurst',
    'ShipmentDrone',
    'Offload',
    'ShipmentBeam',
    'Entrust',
    'Dispatch',
    'Recall',
  ],
  mining: [
    'MiningBoost',
    'MineralStorageCapacity',
    'Enrich',
    'MassMining',
    'HydrogenUpload',
    'MiningUnity',
    'Crunch',
    'Genesis',
    'HydroRocket',
    'MiningDrone',
  ],
  support: [
    'EMP',
    'Teleport',
    'RedStarExtender',
    'Repair',
    'TimeWarp',
    'Unity',
    'Sanctuary',
    'Stealth',
    'Fortify',
    'Impulse',
    'AlphaRocket',
    'Salvage',
    'Supress',
    'Destiny',
    'Barrier',
    'Vengeance',
    'DeltaRocket',
    'Leap',
    'Bond',
    'AlphaDrone',
    'OmegaRocket',
  ],
  shield: [
    'WeakShield',
    'StandardShield',
    'StrongShield',
    'PassiveShield',
    'MirrorShield',
    'AreaShield',
    'BlastShield',
  ],
  weapon: ['WeakBattery', 'Battery', 'Laser', 'MassBattery', 'DualLaser', 'Barrage', 'DartLauncher'],
};

module.exports = {
  someHumanData,
  modulesByTypes,
};
