var modulesByTypes = {
  trade: [
    'TransportCapacity',
    'ShipmentComputer',
    'Trader',
    'Rush',
    'TradeBurst',
    'ShipmentDrone',
    'Offload',
    'ShipmentBeam',
    'Entrust',
    'Dispatch',
    'Recall',
  ],
  mining: [
    'MiningBoost',
    'MineralStorageCapacity',
    'Enrich',
    'MassMining',
    'HydrogenUpload',
    'MiningUnity',
    'Crunch',
    'Genesis',
    'HydroRocket',
    'MiningDrone',
  ],
  support: [
    'EMP',
    'Teleport',
    'RedStarExtender',
    'Repair',
    'TimeWarp',
    'Unity',
    'Sanctuary',
    'Stealth',
    'Fortify',
    'Impulse',
    'AlphaRocket',
    'Salvage',
    'Supress',
    'Destiny',
    'Barrier',
    'Vengeance',
    'DeltaRocket',
    'Leap',
    'Bond',
    'AlphaDrone',
    'Suspend',
    'OmegaRocket',
  ],
  shield: [
    'WeakShield',
    'StandardShield',
    'PassiveShield',
    'StrongShield',
    'MirrorShield',
    'BlastShield',
    'AreaShield',
  ],
  weapon: ['WeakBattery', 'Battery', 'Laser', 'MassBattery', 'DualLaser', 'Barrage', 'DartLauncher'],
};

module.exports = {
  modulesByTypes,
};
