var modulesByTypes = {
  trade: [
    'TransportCapacity',
    'ShipmentComputer',
    'Trader',
    'Rush',
    'TradeBurst',
    'ShipmentDrone',
    'Offload',
    'ShipmentBeam',
    'Entrust',
    'Dispatch',
    'Recall',
  ],
  mining: [
    'MiningBoost',
    'MineralStorageCapacity',
    'Enrich',
    'MassMining',
    'HydrogenUpload',
    'MiningUnity',
    'Crunch',
    'Genesis',
    'HydroRocket',
    'MiningDrone',
  ],
  support: [
    'EMP',
    'Teleport',
    'RedStarExtender',
    'Repair',
    'TimeWarp',
    'Unity',
    'Sanctuary',
    'Stealth',
    'Fortify',
    'Impulse',
    'AlphaRocket',
    'Salvage',
    'Supress',
    'Destiny',
    'Barrier',
    'Vengeance',
    'DeltaRocket',
    'Leap',
    'Bond',
    'AlphaDrone',
    'Suspend',
    'OmegaRocket',
  ],
  shield: [
    'WeakShield',
    'StandardShield',
    'PassiveShield',
    'StrongShield',
    'MirrorShield',
    'BlastShield',
    'AreaShield',
  ],
  weapon: ['WeakBattery', 'Battery', 'Laser', 'MassBattery', 'DualLaser', 'Barrage', 'DartLauncher'],
};

const some = {
  ExtraTradeSlots: 'TID_SHIP_UPGRADE_EFFECT_TRADE_SLOTS',
  FuelUseIncrease: 'TID_SHIP_UPGRADE_EFFECT_FUEL_INCREASE',
  BCCost: 'TID_MODULE_INSTALL_PRICE_STAT',
  WaypointShipmentRewardBonus: 'TID_SHIP_UPGRADE_EFFECT_BONUS_REWARD',
  ActivationDelay: 'TID_MODULE_COOLDOWN_STAT',
  JobPayoutIncreasePercent: 'TID_SHIP_UPGRADE_EFFECT_JOB_PAYOUT_INCREASE',
  ActivationFuelCost: 'TID_MODULE_DESCR_ACTIVATION_COST',
  EffectDurationx10: 'TID_MODULE_EFFECT_DURATION_DESCR',
  MiningSpeedModifierPct: 'TID_MODULE_MINING_SPEED_STAT',
  EffectRadius: 'TID_MODULE_EFFECT_RANGE_DESCR',
  RepairHullPointsPerSecond: 'TID_MODULE_REPAIR_STAT',
  ShieldStrength: 'TID_FLEET_SHIELD_STRENGTH',
  SpeedIncrDuringActivation: 'TID_MODULE_RUSH_SPEED_INCR',
  ActivationPrep: 'TID_MODULE_ACTIVATION_PREP_TIME',
  TradeBurstShipmentsStart: 'TID_MODULE_TRADEBURST_THRESHOLD',
  TradeBurstShipmentBonus: 'TID_SHIP_UPGRADE_EFFECT_BONUS_REWARD',
  TeleportShipments: 'TID_MODULE_SHIPMENTBEAM_MAX_SHIPMENTS',
  InstantHydrogenCollected: 'TID_MODULE_CRUNCH_MAX_AMOUNT',
  Speed: 'TID_FLEET_SPEED',
  HP: 'TID_FLEET_HULL_STRENGTH',
  Damage: 'TID_MODULE_PROJECTILE_DAMAGE',
  DamageRange: 'TID_MODULE_PROJECTILE_DAMAGERANGE',
  IncreaseSectorHydroPct: 'TID_MODULE_ENRICH_INCREASE',
  SpeedIncreasePerShipment: 'TID_MODULE_RUSH_SPEED_INCR',
  MaxNewAsteroids: 'TID_MODULE_GENESIS_MAX_ASTEROIDS',
  HydroPerNewAsteroid: 'TID_MODULE_GENESIS_MAX_HYDRO',
  TradeStationDeliverReward: 'TID_OFFLOAD_MODULE_PAYOFF',
  SpawnLifetime: 'TID_DRONE_LIFETIME',
  DPS: 'TID_MODULE_DESCR_DPS',
  DamageRangeWhenNeutralized: 'TID_MODULE_SECONDARY_RANGE',
  HydrogenCapacity: 'TID_HYDRO_CAPACITY',
  AdditionalDPSPerTargetInRange: 'TID_MODULE_DESCR_DPADT',
  TimeWarpFactor: 'TID_MODULE_TIME_WARP_STAT',
  UnityBoostPercent: 'TID_MODULE_DESCR_UNITY_MINER',
  DamageReductionPct: 'TID_MODULE_DAMAGE_REDUCTION_PCT',
  SalvageHullPercent: 'TID_MODULE_SALVAGE_HULL_DESCR',
  AOEDamage: 'TID_DESTROYER_AREADAMAGE',
  DamageWhenNeutralized: 'TID_MODULE_SECONDARY_DAMAGE',
  SpawnCapacity: 'TID_TRANSPORT_CAPACITY_TOTAL',
  DroneShipmentBonus: 'TID_MODULE_BONUS_PER_SHIPMENT',
  APTPIOTTP: 'TID_DISPATCH_PREP_TIME',
  ExtraMineralStorage: 'TID_MODULE_MINERAL_STORAGE_STAT',
  HydroUploadPct: 'TID_MODULE_HYDRO_UPLOAD_PERCENT',
  MiningSpeed: 'TID_MINER_MINE_SPEED',
  MaxDPS: 'TID_MODULE_DESCR_MAX_DPS',
  MaxTargets: 'TID_MODULE_MAX_TARGETS',
  MirrorDamagePct: 'TID_MODULE_MIRROR_DAMAGE_STAT',
  RedStarLifeExtention: 'TID_MODULE_RED_STAR_EXTENSION_STAT',
};

/*

// "TID_YELLOW_STAR","YELLOW STAR"
// "TID_RED_STAR","RED STAR"
// "TID_HOME_STAR","HOME STAR"

"TID_WHITE_STAR","WHITE STAR"
"TID_BLUE_STAR","BLUE STAR"


*/

const paramsNames = {
  Common: [
    ['___NO_TRANSLATE___', 'blueprints required'],
    ['___NO_TRANSLATE___', 'unlock price'],
    ['___NO_TRANSLATE___', 'research time'],
    ['TID_SHIP_UPGRADE_EFFECT_FUEL_INCREASE', 'ADDITIONAL HYDROGEN USE'],
    ['TID_MODULE_DESCR_ACTIVATION_COST', 'ACTIVATION COST'],
    ['TID_MODULE_INSTALL_PRICE_STAT', 'INSTALL PRICE'],
  ],
  TransportCapacity: [['TID_SHIP_UPGRADE_EFFECT_TRADE_SLOTS', 'ADDITIONAL SLOTS']],
  ShipmentComputer: [
    ['TID_SHIP_UPGRADE_EFFECT_BONUS_REWARD', 'BONUS REWARD'],
    ['TID_MODULE_TRADEBURST_BONUS', 'BONUS REWARD'],
  ],
  Trader: [
    ['TID_MODULE_TRADER', 'TRADE BOOST'],
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['TID_SHIP_UPGRADE_EFFECT_JOB_PAYOUT_INCREASE', 'SHIPMENT REWARD BONUS'],
  ],
  Rush: [
    ['TID_MODULE_RUSH_SPEED_INCR', 'SPEED INCREASE'],
    ['TID_MODULE_RUSH_SPEED_INCR_VAL_PER_SHIPMENT', '+{0}% / SHIPMENT'],
  ],
  TradeBurst: [
    ['TID_MODULE_TRADEBURST_THRESHOLD', 'THRESHOLD'],
    ['TID_SHIP_UPGRADE_EFFECT_BONUS_REWARD', 'BONUS REWARD'],
    ['TID_MODULE_TRADEBURST_BONUS', 'BONUS REWARD'],
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
  ],
  ShipmentDrone: [
    ['TID_TRANSPORT_CAPACITY_TOTAL', 'TOTAL CARGO SLOTS'],
    ['TID_MODULE_BONUS_PER_SHIPMENT', 'BONUS PER ADDITIONAL SHIPMENT'],
    ['___NO_TRANSLATE___', 'max bonus'],
  ],
  Offload: [['TID_OFFLOAD_MODULE_PAYOFF', 'PAYOFF'], ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION']],
  ShipmentBeam: [
    ['TID_MODULE_SHIPMENTBEAM_MAX_SHIPMENTS', 'MAX SHIPMENTS'],
    ['TID_NUM_SHIPMENTS_MAX', 'MAX SHIPMENTS'],
  ],
  Entrust: [['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE']],
  Dispatch: [
    ['TID_DISPATCH_PREP_TIME', 'PREPARATION TIME PER ITEM'],
    ['___NO_TRANSLATE___', 'preparation time per item (white star)'],
  ],
  Recall: [['___NO_TRANSLATE___', '-']],
  MiningBoost: [
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
    ['TID_MODULE_MINING_SPEED_STAT', 'MINING SPEED'],
    ['TID_MINER_MINE_SPEED', 'MINING SPEED'],
  ],

  MineralStorageCapacity: [['TID_MODULE_MINERAL_STORAGE_STAT', 'ADDITIONAL STORAGE']],
  Enrich: [
    ['TID_MODULE_ENRICH_INCREASE', 'HYDROGEN INCREASE'],
    ['TID_MODULE_ENRICH_MAX_CAPACITY_PER_ASTEROID', 'MAX ENRICH AMOUNT'],
  ],
  MassMining: [['TID_MODULE_MINING_SPEED_STAT', 'MINING SPEED'], ['TID_MINER_MINE_SPEED', 'MINING SPEED']],
  HydrogenUpload: [['TID_MODULE_HYDRO_UPLOAD_PERCENT', 'PERCENT UPLOADED']],
  MiningUnity: [
    ['TID_MODULE_DESCR_UNITY_MINER', 'SPEED INCREASE PER PLAYER'],
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
  ],
  Crunch: [['TID_MODULE_CRUNCH_MAX_AMOUNT', 'MAX AMOUNT']],
  Genesis: [
    ['TID_MODULE_GENESIS_MAX_ASTEROIDS', 'MAX NEW ASTEROIDS'],
    ['TID_MODULE_GENESIS_MAX_HYDRO', 'MAX NEW HYDROGEN'],
  ],
  HydroRocket: [
    ['TID_REQUIRED_HYDROGEN', 'REQUIRED HYDROGEN'],
    ['TID_FLEET_HULL_STRENGTH', 'HULL STRENGTH'],
    ['TID_CERBERUS_STATION_HULL_LABEL', 'HULL STRENGTH'],
    ['TID_MODULE_PROJECTILE_DAMAGE', 'EXPLOSION DAMAGE'],
    ['TID_MODULE_PROJECTILE_DAMAGERANGE', 'EXPLOSION RANGE'],
  ],
  MiningDrone: [
    ['TID_FLEET_HULL_STRENGTH', 'HULL STRENGTH'],
    ['TID_CERBERUS_STATION_HULL_LABEL', 'HULL STRENGTH'],
    ['TID_MODULE_MINING_SPEED_STAT', 'MINING SPEED'],
    ['TID_MINER_MINE_SPEED', 'MINING SPEED'],
    ['TID_HYDRO_CAPACITY_TOTAL', 'TOTAL HYDROGEN CAPACITY'],
  ],
  WeakBattery: [
    ['TID_MODULE_DESCR_DPS', 'DAMAGE PER SECOND'],
    ['TID_FLEET_DPM', 'DAMAGE PER SECOND'],
    ['TID_CERBERUS_STATION_ATTACK_DAMAGE', 'DAMAGE PER SECOND'],
    ['___NO_TRANSLATE___', 'damage per hour (white star)'],
  ],
  Battery: [
    ['TID_MODULE_DESCR_DPS', 'DAMAGE PER SECOND'],
    ['TID_FLEET_DPM', 'DAMAGE PER SECOND'],
    ['TID_CERBERUS_STATION_ATTACK_DAMAGE', 'DAMAGE PER SECOND'],
    ['___NO_TRANSLATE___', 'damage per hour (white star)'],
  ],
  Laser: [
    ['TID_MODULE_DESCR_DPS', 'DAMAGE PER SECOND'],
    ['TID_FLEET_DPM', 'DAMAGE PER SECOND'],
    ['TID_CERBERUS_STATION_ATTACK_DAMAGE', 'DAMAGE PER SECOND'],
    ['TID_MODULE_DESCR_MAX_DPS', 'MAXIMUM DAMAGE PER SECOND'],
    ['___NO_TRANSLATE___', 'time to maximum damage (red star)'],
    ['___NO_TRANSLATE___', 'damage per hour (white star)'],
    ['___NO_TRANSLATE___', 'maximum damage per hour (white star)'],
    ['___NO_TRANSLATE___', 'time to maximum damage (white star)'],
    ['___NO_TRANSLATE___', 'time to maximum damage (blue star)'],
  ],
  MassBattery: [
    ['TID_MODULE_DESCR_DPS', 'DAMAGE PER SECOND'],
    ['TID_FLEET_DPM', 'DAMAGE PER SECOND'],
    ['TID_CERBERUS_STATION_ATTACK_DAMAGE', 'DAMAGE PER SECOND'],
    ['___NO_TRANSLATE___', 'damage per hour (white star)'],
    ['TID_MODULE_MAX_TARGETS', 'MAX TARGETS'],
  ],
  DualLaser: [
    ['TID_MODULE_DESCR_DPS', 'DAMAGE PER SECOND'],
    ['TID_FLEET_DPM', 'DAMAGE PER SECOND'],
    ['TID_CERBERUS_STATION_ATTACK_DAMAGE', 'DAMAGE PER SECOND'],
    ['TID_MODULE_DESCR_MAX_DPS', 'MAXIMUM DAMAGE PER SECOND'],
    ['TID_MODULE_DESCR_MAX_DPS_TIME', 'TIME TO MAXIMUM DAMAGE'],
    ['___NO_TRANSLATE___', 'damage per hour (white star)'],
    ['___NO_TRANSLATE___', 'maximum damage per hour (white star)'],
    ['___NO_TRANSLATE___', 'time to maximum damage (white star)'],
    ['___NO_TRANSLATE___', 'time to maximum damage (blue star)'],
    ['TID_MODULE_MAX_TARGETS', 'MAX TARGETS'],
  ],
  Barrage: [
    ['TID_MODULE_DESCR_DPS', 'DAMAGE PER SECOND'],
    ['TID_FLEET_DPM', 'DAMAGE PER SECOND'],
    ['TID_CERBERUS_STATION_ATTACK_DAMAGE', 'DAMAGE PER SECOND'],
    ['___NO_TRANSLATE___', 'additional damage per enemy'],
    ['___NO_TRANSLATE___', 'maximum damage'],
    ['___NO_TRANSLATE___', 'damage per hour (white star)'],
    ['___NO_TRANSLATE___', 'additional damage per enemy (white star)'],
    ['___NO_TRANSLATE___', 'maximum damage (white star)'],
  ],
  DartLauncher: [
    ['TID_FLEET_HULL_STRENGTH', 'HULL STRENGTH'],
    ['TID_CERBERUS_STATION_HULL_LABEL', 'HULL STRENGTH'],
    ['TID_MODULE_PROJECTILE_DAMAGE', 'EXPLOSION DAMAGE'],
    ['TID_MODULE_PROJECTILE_DAMAGERANGE', 'EXPLOSION RANGE'],
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
  ],
  WeakShield: [
    ['TID_MODULE_SHIELD_STRENGTH_STAT', 'SHIELD STRENGTH'],
    ['TID_FLEET_SHIELD_STRENGTH', 'SHIELD STRENGTH'],
    ['TID_CERBERUS_STATION_SHIELD_LABEL', 'SHIELD STRENGTH'],
  ],
  StandardShield: [
    ['TID_MODULE_SHIELD_STRENGTH_STAT', 'SHIELD STRENGTH'],
    ['TID_FLEET_SHIELD_STRENGTH', 'SHIELD STRENGTH'],
    ['TID_CERBERUS_STATION_SHIELD_LABEL', 'SHIELD STRENGTH'],
    ['TID_MODULE_SPEED_INCR_ACTIVATION', 'SPEED INCREASE'],
    ['TID_MODULE_RUSH_SPEED_INCR', 'SPEED INCREASE'],
  ],
  PassiveShield: [
    ['TID_MODULE_SHIELD_STRENGTH_STAT', 'SHIELD STRENGTH'],
    ['TID_FLEET_SHIELD_STRENGTH', 'SHIELD STRENGTH'],
    ['TID_CERBERUS_STATION_SHIELD_LABEL', 'SHIELD STRENGTH'],
  ],
  StrongShield: [
    ['TID_MODULE_SHIELD_STRENGTH_STAT', 'SHIELD STRENGTH'],
    ['TID_FLEET_SHIELD_STRENGTH', 'SHIELD STRENGTH'],
    ['TID_CERBERUS_STATION_SHIELD_LABEL', 'SHIELD STRENGTH'],
  ],
  MirrorShield: [
    ['TID_MODULE_SHIELD_STRENGTH_STAT', 'SHIELD STRENGTH'],
    ['TID_FLEET_SHIELD_STRENGTH', 'SHIELD STRENGTH'],
    ['TID_CERBERUS_STATION_SHIELD_LABEL', 'SHIELD STRENGTH'],
    ['TID_MODULE_MIRROR_DAMAGE_STAT', 'DAMAGE MIRRORED'],
  ],
  BlastShield: [
    ['TID_MODULE_SHIELD_STRENGTH_STAT', 'SHIELD STRENGTH'],
    ['TID_FLEET_SHIELD_STRENGTH', 'SHIELD STRENGTH'],
    ['TID_CERBERUS_STATION_SHIELD_LABEL', 'SHIELD STRENGTH'],
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
  ],
  AreaShield: [
    ['TID_MODULE_SHIELD_STRENGTH_STAT', 'SHIELD STRENGTH'],
    ['TID_FLEET_SHIELD_STRENGTH', 'SHIELD STRENGTH'],
    ['TID_CERBERUS_STATION_SHIELD_LABEL', 'SHIELD STRENGTH'],
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
  ],
  EMP: [
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
    ['___NO_TRANSLATE___', 'effect duration (blue star)'],
  ],
  Teleport: [
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['___NO_TRANSLATE___', 'effect range (white star)'],
    ['___NO_TRANSLATE___', 'effect range (blue star)'],
    ['___NO_TRANSLATE___', 'maximum travel efficiency (red star)'],
  ],
  RedStarExtender: [['TID_MODULE_RED_STAR_EXTENSION_STAT', 'LIFE EXTENSION']],
  Repair: [
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
    ['___NO_TRANSLATE___', 'effect duration (blue star)'],
    ['___NO_TRANSLATE___', 'hp repair rate'],
    ['___NO_TRANSLATE___', 'hp repair rate (white star)'],
    ['___NO_TRANSLATE___', 'total hp repaired'],
    ['___NO_TRANSLATE___', 'total hp repaired (blue star)'],
  ],
  TimeWarp: [
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['___NO_TRANSLATE___', 'real time effect duration'],
    ['___NO_TRANSLATE___', 'listed effect duration'],
    ['___NO_TRANSLATE___', 'real time effect duration (white star)'],
    ['___NO_TRANSLATE___', 'listed effect duration (white star)'],
    ['TID_MODULE_TIME_WARP_STAT', 'TIME FACTOR'],
  ],
  Unity: [
    ['TID_MODULE_DESCR_UNITY', 'DAMAGE INCREASE PER PLAYER'],
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
  ],
  Sanctuary: [],
  Stealth: [
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
    ['___NO_TRANSLATE___', 'effect duration (blue star)'],
  ],
  Fortify: [
    ['TID_MODULE_DAMAGE_REDUCTION_PCT', 'DAMAGE REDUCTION'],
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
    ['___NO_TRANSLATE___', 'effect duration (blue star)'],
  ],
  Impulse: [
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
    ['___NO_TRANSLATE___', 'effect duration (blue star)'],
  ],
  AlphaRocket: [
    ['TID_FLEET_HULL_STRENGTH', 'HULL STRENGTH'],
    ['TID_CERBERUS_STATION_HULL_LABEL', 'HULL STRENGTH'],
    ['TID_MODULE_PROJECTILE_DAMAGE', 'EXPLOSION DAMAGE'],
    ['TID_MODULE_PROJECTILE_DAMAGERANGE', 'EXPLOSION RANGE'],
  ],
  Salvage: [
    ['TID_MODULE_SALVAGE_HULL_DESCR', 'HULL REPAIRED PER DESTROYED SHIP'],
    ['___NO_TRANSLATE___', 'hull repaired per destroyed ship (white star)'],
  ],
  Supress: [
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
    ['___NO_TRANSLATE___', 'effect range (blue star)'],
  ],
  Destiny: [
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['TID_MODULE_AOE_STAT', 'AREA DAMAGE'],
    ['___NO_TRANSLATE___', 'area damage (white star)'],
    ['___NO_TRANSLATE___', 'area damage (blue star)'],
  ],
  Barrier: [
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
    ['___NO_TRANSLATE___', 'effect range (blue star)'],
    ['___NO_TRANSLATE___', 'effect duration (blue star)'],
  ],
  Vengeance: [
    ['TID_MODULE_HULL_THRESHOLD_STAT', 'HULL STRENGTH THRESHOLD'],
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['TID_MODULE_AOE_STAT', 'AREA DAMAGE'],
    ['___NO_TRANSLATE___', 'area damage (white star)'],
    ['___NO_TRANSLATE___', 'area damage (blue star)'],
  ],
  DeltaRocket: [
    ['TID_FLEET_HULL_STRENGTH', 'HULL STRENGTH'],
    ['TID_CERBERUS_STATION_HULL_LABEL', 'HULL STRENGTH'],
    ['TID_MODULE_PROJECTILE_DAMAGE', 'EXPLOSION DAMAGE'],
    ['TID_MODULE_PROJECTILE_DAMAGERANGE', 'EXPLOSION RANGE'],
  ],
  Leap: [
    ['TID_MODULE_ACTIVATION_PREP_TIME', 'ACTIVATION DELAY'],
    ['___NO_TRANSLATE___', 'activation delay (white star)'],
    ['TID_MODULE_LEAP_DISABLE_STAT', 'DISABLE TIME'],
    ['___NO_TRANSLATE___', 'disable time (white star)'],
  ],
  Bond: [
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['TID_MODULE_EFFECT_DURATION_DESCR', 'EFFECT DURATION'],
    ['___NO_TRANSLATE___', 'effect duration (white star)'],
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['___NO_TRANSLATE___', 'effect duration (blue star)'],
  ],
  AlphaDrone: [
    ['TID_MODULE_DESCR_DPS', 'DAMAGE PER SECOND'],
    ['TID_FLEET_DPM', 'DAMAGE PER SECOND'],
    ['TID_CERBERUS_STATION_ATTACK_DAMAGE', 'DAMAGE PER SECOND'],
    ['___NO_TRANSLATE___', 'damage per hour (white star)'],
    ['TID_FLEET_HULL_STRENGTH', 'HULL STRENGTH'],
    ['TID_CERBERUS_STATION_HULL_LABEL', 'HULL STRENGTH'],
  ],
  Suspend: [
    ['TID_MODULE_EFFECT_RANGE_DESCR', 'EFFECT RANGE'],
    ['___NO_TRANSLATE___', 'real time effect duration'],
    ['___NO_TRANSLATE___', 'listed effect duration'],
    ['___NO_TRANSLATE___', 'real time effect duration (white star)'],
    ['___NO_TRANSLATE___', 'listed effect duration (white star)'],
    ['TID_MODULE_TIME_WARP_STAT', 'TIME FACTOR'],
  ],
  OmegaRocket: [
    ['TID_FLEET_HULL_STRENGTH', 'HULL STRENGTH'],
    ['TID_CERBERUS_STATION_HULL_LABEL', 'HULL STRENGTH'],
    ['TID_MODULE_PROJECTILE_DAMAGE', 'EXPLOSION DAMAGE'],
    ['TID_MODULE_PROJECTILE_DAMAGERANGE', 'EXPLOSION RANGE'],
    ['TID_MODULE_SECONDARY_DAMAGE', 'NEUTRALIZED DAMAGE'],
    ['TID_MODULE_SECONDARY_RANGE', 'NEUTRALIZED DAMAGE RANGE'],
  ],
};

module.exports = {
  modulesByTypes,
};
